---
deployment:
  tasks:
    - echo "Starting deployment..."

    - export DEPLOYPATH=/home/cindernw/public_html
    - export BUILDPATH=/home/cindernw/repositories/Cinder/cinder-app/frontend/cinderWeb/dist

    - echo "Cleaning old files..."
    - rm -rf $DEPLOYPATH/*

    - echo "Copying new build files..."
    - cp -r $BUILDPATH/* $DEPLOYPATH/

    - echo "Deployment complete."