import orjson

# reads the json generated by grib_data_to_json.py
with open("href12z_for_41.5623,-72.6506.json", "rb") as f:
    parsed = orjson.loads(f.read())


metadata = parsed["metadata"]
data = parsed["data"]

print("Model:", metadata["sitrep"])
print("Forecast time:", metadata["forecast_time"])
print("Location:", metadata["location"])
print("Available fields:", metadata["forecast_types"])

# show first few records
for record in data[:5]:
    print(record)